image: node:lts

stages:
  - validation
  - test
  - deploy


.modules: &modules
  - cd client && npm install

lint:
  stage: validation
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE != "pipeline"
  before_script:
    - *modules
  script:
    - npm run lint:check

test:
  stage: test
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE != "pipeline"
  before_script:
    - *modules
  script:
    - npm run test

build-image:
  image: docker:24.0.5
  stage: deploy
  environment:
    name: production
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    FRONTEND_TAG: ${CI_REGISTRY_IMAGE}/client:${CI_ENVIRONMENT_NAME}
  needs: [lint, test]
  rules:
    - if: $CI_PIPELINE_SOURCE != "pipeline"
  before_script:
    - *modules
    - npm run build
  script:
    - docker build --no-cache -f docker/client/client.dockerfile -t ${FRONTEND_TAG}
    - docker push ${FRONTEND_TAG}