import { EditorState } from 'draft-js'
import dynamic from 'next/dynamic'
import { EditorProps as DraftEditorProps } from 'react-draft-wysiwyg'
import 'react-draft-wysiwyg/dist/react-draft-wysiwyg.css'
import './wysiwyg-editor.css'

const Editor = dynamic<DraftEditorProps>(() => import('react-draft-wysiwyg').then((mod) => mod.Editor), { ssr: false })

export function WysiwygEditor({
    editorState,
    setEditorState,
}: {
    editorState: EditorState
    setEditorState: (editorState: EditorState) => void
}) {
    return (
        <Editor
            editorState={editorState}
            toolbarClassName="wysiwyg-toolbar"
            wrapperClassName="wysiwyg-wrapper"
            editorClassName="wysiwyg-editor"
            onEditorStateChange={setEditorState}
            placeholder={"Description de l'événement"}
            toolbar={toolbarOptions}
        />
    )
}

const toolbarOptions = {
    options: ['inline', 'blockType', 'fontSize', 'textAlign', 'list', 'colorPicker', 'history', 'emoji'],
    blockType: {
        inDropdown: true,
        options: ['Normal', 'H1', 'H2', 'H3', 'Blockquote', 'Code'],
    },
    fontSize: {
        inDropdown: true,
        options: [8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72, 96],
    },
    textAlign: {
        inDropdown: true,
        options: ['left', 'center', 'right', 'justify'],
    },
    inline: { inDropdown: true, options: ['bold', 'italic', 'underline'] },
    list: { inDropdown: true, options: ['unordered', 'ordered'] },
    colorPicker: {
        inDropdown: true,
        colors: [
            'rgb(97,189,109)',
            'rgb(26,188,156)',
            'rgb(84,172,210)',
            'rgb(44,130,201)',
            'rgb(147,101,184)',
            'rgb(71,85,119)',
            'rgb(204,204,204)',
            'rgb(65,168,95)',
            'rgb(0,168,133)',
            'rgb(61,142,185)',
            'rgb(41,105,176)',
            'rgb(85,57,130)',
            'rgb(40,50,78)',
            'rgb(0,0,0)',
            'rgb(247,218,100)',
            'rgb(251,160,38)',
            'rgb(235,107,86)',
            'rgb(226,80,65)',
            'rgb(163,143,132)',
            'rgb(239,239,239)',
            'rgb(255,255,255)',
            'rgb(250,197,28)',
            'rgb(243,121,52)',
            'rgb(209,72,65)',
            'rgb(184,49,47)',
            'rgb(124,112,107)',
            'rgb(209,213,216)',
        ],
    },
    emoji: {
        inDropdown: true,
        emojis: [
            '😀',
            '😁',
            '😂',
            '😃',
            '😉',
            '😋',
            '😎',
            '😍',
            '😗',
            '🤗',
            '🤔',
            '😣',
            '😫',
            '😴',
            '😌',
            '🤓',
            '😛',
            '😜',
            '😠',
            '😇',
            '😷',
            '😈',
            '👻',
            '😺',
            '😸',
            '😹',
            '😻',
            '😼',
            '😽',
            '🙀',
            '🙈',
            '🙉',
            '🙊',
            '👼',
            '👮',
            '🕵',
            '💂',
            '👳',
            '🎅',
            '👸',
            '👰',
            '👲',
            '🙍',
            '🙇',
            '🚶',
            '🏃',
            '💃',
            '⛷',
            '🏂',
            '🏌',
            '🏄',
            '🚣',
            '🏊',
            '⛹',
            '🏋',
            '🚴',
            '👫',
            '💪',
            '👈',
            '👉',
            '👉',
            '👆',
            '🖕',
            '👇',
            '🖖',
            '🤘',
            '🖐',
            '👌',
            '👍',
            '👎',
            '✊',
            '👊',
            '👏',
            '🙌',
            '🙏',
            '🐵',
            '🐶',
            '🐇',
            '🐥',
            '🐸',
            '🐌',
            '🐛',
            '🐜',
            '🐝',
            '🍉',
            '🍄',
            '🍔',
            '🍤',
            '🍨',
            '🍪',
            '🎂',
            '🍰',
            '🍾',
            '🍷',
            '🍸',
            '🍺',
            '🌍',
            '🚑',
            '⏰',
            '🌙',
            '🌝',
            '🌞',
            '⭐',
            '🌟',
            '🌠',
            '🌨',
            '🌩',
            '⛄',
            '🔥',
            '🎄',
            '🎈',
            '🎉',
            '🎊',
            '🎁',
            '🎗',
            '🏀',
            '🏈',
            '🎲',
            '🔇',
            '🔈',
            '📣',
            '🔔',
            '🎵',
            '🎷',
            '💰',
            '🖊',
            '📅',
            '✅',
            '❎',
            '💯',
        ],
    },
    history: { inDropdown: true },
}
