export type DepartmentDetails = {
    dep_name: string
    region_name: string
}

export type DepartmentsList = {
    [key: string]: DepartmentDetails
}
export const departmentsList: DepartmentsList = {
    '01': { dep_name: 'Ain', region_name: 'Auvergne-Rhône-Alpes' },
    '02': { dep_name: 'Aisne', region_name: 'Hauts-de-France' },
    '03': { dep_name: 'Allier', region_name: 'Auvergne-Rhône-Alpes' },
    '04': { dep_name: 'Alpes-de-Haute-Provence', region_name: "Provence-Alpes-Côte d'Azur" },
    '05': { dep_name: 'Hautes-Alpes', region_name: "Provence-Alpes-Côte d'Azur" },
    '06': { dep_name: 'Alpes-Maritimes', region_name: "Provence-Alpes-Côte d'Azur" },
    '07': { dep_name: 'Ardèche', region_name: 'Auvergne-Rhône-Alpes' },
    '08': { dep_name: 'Ardennes', region_name: 'Grand Est' },
    '09': { dep_name: 'Ariège', region_name: 'Occitanie' },
    '10': { dep_name: 'Aube', region_name: 'Grand Est' },
    '11': { dep_name: 'Aude', region_name: 'Occitanie' },
    '12': { dep_name: 'Aveyron', region_name: 'Occitanie' },
    '13': { dep_name: 'Bouches-du-Rhône', region_name: "Provence-Alpes-Côte d'Azur" },
    '14': { dep_name: 'Calvados', region_name: 'Normandie' },
    '15': { dep_name: 'Cantal', region_name: 'Auvergne-Rhône-Alpes' },
    '16': { dep_name: 'Charente', region_name: 'Nouvelle-Aquitaine' },
    '17': { dep_name: 'Charente-Maritime', region_name: 'Nouvelle-Aquitaine' },
    '18': { dep_name: 'Cher', region_name: 'Centre-Val de Loire' },
    '19': { dep_name: 'Corrèze', region_name: 'Nouvelle-Aquitaine' },
    '21': { dep_name: "Côte-d'Or", region_name: 'Bourgogne-Franche-Comté' },
    '22': { dep_name: "Côtes-d'Armor", region_name: 'Bretagne' },
    '23': { dep_name: 'Creuse', region_name: 'Nouvelle-Aquitaine' },
    '24': { dep_name: 'Dordogne', region_name: 'Nouvelle-Aquitaine' },
    '25': { dep_name: 'Doubs', region_name: 'Bourgogne-Franche-Comté' },
    '26': { dep_name: 'Drôme', region_name: 'Auvergne-Rhône-Alpes' },
    '27': { dep_name: 'Eure', region_name: 'Normandie' },
    '28': { dep_name: 'Eure-et-Loir', region_name: 'Centre-Val de Loire' },
    '29': { dep_name: 'Finistère', region_name: 'Bretagne' },
    '2A': { dep_name: 'Corse-du-Sud', region_name: 'Corse' },
    '2B': { dep_name: 'Haute-Corse', region_name: 'Corse' },
    '30': { dep_name: 'Gard', region_name: 'Occitanie' },
    '31': { dep_name: 'Haute-Garonne', region_name: 'Occitanie' },
    '32': { dep_name: 'Gers', region_name: 'Occitanie' },
    '33': { dep_name: 'Gironde', region_name: 'Nouvelle-Aquitaine' },
    '34': { dep_name: 'Hérault', region_name: 'Occitanie' },
    '35': { dep_name: 'Ille-et-Vilaine', region_name: 'Bretagne' },
    '36': { dep_name: 'Indre', region_name: 'Centre-Val de Loire' },
    '37': { dep_name: 'Indre-et-Loire', region_name: 'Centre-Val de Loire' },
    '38': { dep_name: 'Isère', region_name: 'Auvergne-Rhône-Alpes' },
    '39': { dep_name: 'Jura', region_name: 'Bourgogne-Franche-Comté' },
    '40': { dep_name: 'Landes', region_name: 'Nouvelle-Aquitaine' },
    '41': { dep_name: 'Loir-et-Cher', region_name: 'Centre-Val de Loire' },
    '42': { dep_name: 'Loire', region_name: 'Auvergne-Rhône-Alpes' },
    '43': { dep_name: 'Haute-Loire', region_name: 'Auvergne-Rhône-Alpes' },
    '44': { dep_name: 'Loire-Atlantique', region_name: 'Pays de la Loire' },
    '45': { dep_name: 'Loiret', region_name: 'Centre-Val de Loire' },
    '46': { dep_name: 'Lot', region_name: 'Occitanie' },
    '47': { dep_name: 'Lot-et-Garonne', region_name: 'Nouvelle-Aquitaine' },
    '48': { dep_name: 'Lozère', region_name: 'Occitanie' },
    '49': { dep_name: 'Maine-et-Loire', region_name: 'Pays de la Loire' },
    '50': { dep_name: 'Manche', region_name: 'Normandie' },
    '51': { dep_name: 'Marne', region_name: 'Grand Est' },
    '52': { dep_name: 'Haute-Marne', region_name: 'Grand Est' },
    '53': { dep_name: 'Mayenne', region_name: 'Pays de la Loire' },
    '54': { dep_name: 'Meurthe-et-Moselle', region_name: 'Grand Est' },
    '55': { dep_name: 'Meuse', region_name: 'Grand Est' },
    '56': { dep_name: 'Morbihan', region_name: 'Bretagne' },
    '57': { dep_name: 'Moselle', region_name: 'Grand Est' },
    '58': { dep_name: 'Nièvre', region_name: 'Bourgogne-Franche-Comté' },
    '59': { dep_name: 'Nord', region_name: 'Hauts-de-France' },
    '60': { dep_name: 'Oise', region_name: 'Hauts-de-France' },
    '61': { dep_name: 'Orne', region_name: 'Normandie' },
    '62': { dep_name: 'Pas-de-Calais', region_name: 'Hauts-de-France' },
    '63': { dep_name: 'Puy-de-Dôme', region_name: 'Auvergne-Rhône-Alpes' },
    '64': { dep_name: 'Pyrénées-Atlantiques', region_name: 'Nouvelle-Aquitaine' },
    '65': { dep_name: 'Hautes-Pyrénées', region_name: 'Occitanie' },
    '66': { dep_name: 'Pyrénées-Orientales', region_name: 'Occitanie' },
    '67': { dep_name: 'Bas-Rhin', region_name: 'Grand Est' },
    '68': { dep_name: 'Haut-Rhin', region_name: 'Grand Est' },
    '69': { dep_name: 'Rhône', region_name: 'Auvergne-Rhône-Alpes' },
    '70': { dep_name: 'Haute-Saône', region_name: 'Bourgogne-Franche-Comté' },
    '71': { dep_name: 'Saône-et-Loire', region_name: 'Bourgogne-Franche-Comté' },
    '73': { dep_name: 'Sarthe', region_name: 'Pays de la Loire' },
    '74': { dep_name: 'Savoie', region_name: 'Auvergne-Rhône-Alpes' },
    '75': { dep_name: 'Paris', region_name: 'Île-de-France' },
    '76': { dep_name: 'Seine-Maritime', region_name: 'Normandie' },
    '77': { dep_name: 'Seine-et-Marne', region_name: 'Île-de-France' },
    '78': { dep_name: 'Yvelines', region_name: 'Île-de-France' },
    '79': { dep_name: 'Deux-Sèvres', region_name: 'Nouvelle-Aquitaine' },
    '80': { dep_name: 'Somme', region_name: 'Hauts-de-France' },
    '81': { dep_name: 'Tarn', region_name: 'Occitanie' },
    '82': { dep_name: 'Tarn-et-Garonne', region_name: 'Occitanie' },
    '83': { dep_name: 'Var', region_name: "Provence-Alpes-Côte d'Azur" },
    '84': { dep_name: 'Vaucluse', region_name: "Provence-Alpes-Côte d'Azur" },
    '85': { dep_name: 'Vendée', region_name: 'Pays de la Loire' },
    '86': { dep_name: 'Vienne', region_name: 'Nouvelle-Aquitaine' },
    '87': { dep_name: 'Haute-Vienne', region_name: 'Nouvelle-Aquitaine' },
    '88': { dep_name: 'Vosges', region_name: 'Grand Est' },
    '89': { dep_name: 'Yonne', region_name: 'Bourgogne-Franche-Comté' },
    '90': { dep_name: 'Territoire de Belfort', region_name: 'Bourgogne-Franche-Comté' },
    '91': { dep_name: 'Essonne', region_name: 'Île-de-France' },
    '92': { dep_name: 'Hauts-de-Seine', region_name: 'Île-de-France' },
    '93': { dep_name: 'Seine-Saint-Denis', region_name: 'Île-de-France' },
    '94': { dep_name: 'Val-de-Marne', region_name: 'Île-de-France' },
    '95': { dep_name: "Val-d'Oise", region_name: 'Île-de-France' },
    '971': { dep_name: 'Guadeloupe', region_name: 'Guadeloupe' },
    '972': { dep_name: 'Martinique', region_name: 'Martinique' },
    '973': { dep_name: 'Guyane', region_name: 'Guyane' },
    '974': { dep_name: 'La Réunion', region_name: 'La Réunion' },
    '976': { dep_name: 'Mayotte', region_name: 'Mayotte' },
    'not-defined': { dep_name: '', region_name: '' },
}
